# 实验名称
experiment: "SAN Tuning"

# 随机种子
seed: 20200814

# 训练参数
epoches: 10
batch_size: 8 # tune
workers: 0
optimizer: Adadelta # tune
lr: 1 # tune
lr_decay: cosine # tune
step_ratio: 10 # tune
eps: 1e-6
weight_decay: 1e-4 # tune
beta: 0.9
image_resize: True
image_width: 400
image_height: 150
image_channel: 1
dropout: True # tune
dropout_ratio: 0.5 # tune
relu: True # tune
gradient: 100 # tune
gradient_clip: True # tune
use_label_mask: False # tune

# 训练数据
train_image_path: 'data/train_image.pkl'
train_label_path: 'data/train_label.pkl'
eval_image_path: 'data/test_image.pkl'
eval_label_path: 'data/test_label.pkl'

word_path: 'data/word.txt'

# 选择encoder
encoder:
  net: DenseNet
  input_channels: 1
  out_channels: 684

resnet:
  conv1_stride: 1

densenet:
  ratio: 16
  growthRate: 24
  reduction: 0.5
  bottleneck: True
  use_dropout: True

# 使用的rnn cell
decoder:
  net: SAN_decoder
  cell: 'GRU'
  input_size: 256
  hidden_size: 256

# attention 参数
attention:
  attention_dim: 512

# hybrid tree
hybrid_tree:
  threshold: 0.5

# 训练权重存放路径
optimizer_save: False
checkpoint_dir: 'checkpoints'
finetune: False
checkpoint: ""

# tensorboard路径
log_dir: 'logs'